### ISSUE TITLE
Ignore www, when checking if domain supported

### ISSUE THREAD

**Issue by NoPlagiarism** [httpjamesm/launchpad-redirects#14]
As mentioned in #12, `www` in tiktok isn't supported

But it's hardcoded in [reddit](https://github.com/httpjamesm/launchpad-redirects/blob/5fee6e8089078dd8753ab851bc83b0c30821130c/lists/reddit.go) & [imdb](https://github.com/httpjamesm/launchpad-redirects/blob/5fee6e8089078dd8753ab851bc83b0c30821130c/lists/imdb.go)

**Comment by privacytime101** [comment]
Fixed in #16
